### PR TITLE
Local ITC

### PR DESCRIPTION
**Pull request by cquiroz**
The ITC code is used and maintained in the OCS and uses scala 2.11 and legacy libraries like scalaz/argonaut/etc
To keep `lucuma-itc` on scala 3 the old code was wrapped in a server and `lucuma-itc` would connect via http acting as a proxy and traslation layer
This has a performance impact which become more evident with the support of signal @ wavelength, as that feature requires transferring more data back and forth.

This PR changes the logic and uses the legacy code directly. To avoid clashes the code is called using reflection with a separate classloader. Params are stringified vias json encoding, essentially converting the remote json call into  a local one

Quite a bit of work was required to properly get this to deploy to heroku but the performance improvement is noticeable. This will also be easier to scale.

### CODE REVIEW

**Comment by tpolecat** [comment]
oh no

**Review by tpolecat — APPROVED** [review]
The loading logic is a little weird but all things classloader are weird and if it seems to work that's probably the best we can hope for. Anyway thanks, I hate it. 👍🏻

**Comment by swalker2m** [comment]
Seems worth some jiggery-pokery for the kind of improvement (> 10x ?) we're talking about.

**Comment by cquiroz** [comment]
We went (measured on explore) from 7-10 secs to 200-300 millis so it should be very noticeable. Still we are doing quite a bit of caching.

The regular classloaders will first delegate to the system classloader and then to the extra jars. This will produce a conflict with scala classes thus we need a reverted classloader that will go to the extra jars first.

**Pull request merged**
