### PR TITLE
Preferred result

### PR DESCRIPTION
**Pull request by cquiroz**
In some cases (e.g. imaging) we get more than one result when calculating the exposure time. For example for GMOS we get three results (one per CCD)

 In the imaging case we want to use the second entry for CCD

This PR adds a `preferredIndex` field that will let clients know which result they should use

### CODE REVIEW

**Review by swalker2m — APPROVED** [review]
This looks good.  :+1:

In the ODB API, there are similar cases where there are multiple values but a single one of them is selected.  For example, `ConfigChangeEstimate`s for an `AllConfigChangeEstimes` object.  In that case in addition to the equivalent of a `results` array (which we call `all`) and a `preferredIndex` (which we call `index`), there is also a `selected` field which contains the chosen `ConfigChangeEstimate`.  This is just the value at the index but since that is what a caller is likely most interested in it seemed convenient to include it.  In fact the ODB would ignore the other results and the index if there were a `selected` field.  I mention it just in case we want to make the two cases more similar in a future PR.

**Comment by swalker2m** [comment]
In fact there is even a [`ZipperCodec`](https://github.com/gemini-hlsw/lucuma-odb/blob/main/modules/schema/src/main/scala/lucuma/odb/json/zipper.scala) that is used, which could be extracted to `core` perhaps.

**Comment by cquiroz** [comment]
That seems good, it would be good to be consistent. It would break odb and explore but so be it

**Comment by toddburnside** [comment]
> That seems good, it would be good to be consistent. It would break odb and explore but so be it

I'll be breaking a lot of the same places in `schemas` and `explore` with all of the codecs I am moving. I can remove the zipper codec from `odb` and update `schemas` and `explore` after you update `core`.

**Comment by cquiroz** [comment]
This is now updated to match the way `lucuma-odb` serializes `Zipper`

**Review by swalker2m — APPROVED** [review]
Nice. :+1:

**Pull request merged**
